name: YouTube Live Stream
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install ffmpeg
      run: sudo apt update && sudo apt install -y ffmpeg
    - name: Live
      run: |
        curl -L -o new_video.mp4 "আপনার_নতুন_ভিডিওর_লিংক_এখানে"
        ffmpeg -re -stream_loop -1 -i new_video.mp4 -c:v libx264 -preset veryfast -b:v 3000k -maxrate 3000k -bufsize 6000k -pix_fmt yuv420p -g 50 -c:a aac -b:a 128k -ar 44100 -f flv "rtmp://a.rtmp.youtube.com/live2/আপনার_স্ট্রিম_কি_এখানে"
