name: YouTube Live Stream
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install ffmpeg
      run: sudo apt update && sudo apt install -y ffmpeg
    - name: Download Video
      run: curl -L -o 1229.mp4 "আপনার_ভিডিওর_লিংক_এখানে"
    - name: Stream to YouTube
      run: ffmpeg -re -stream_loop -1 -i 1229.mp4 -vcodec libx264 -preset veryfast -maxrate 3000k -bufsize 6000k -pix_fmt yuv420p -g 50 -c:a aac -b:a 128k -f flv "rtmp://a.rtmp.youtube.com/live2/আপনার_স্ট্রিম_কি_এখানে"
